import { env } from '@/env'

/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Connect -Ticket API
 * OpenAPI spec version: 0.0.1
 */
export type PostSubscriptionsBody = {
  name: string
  email: string
  /** @nullable */
  referrer?: string | null
}

export type PostSubscriptions201 = {
  subscriberId: string
}

/**
 * @nullable
 */
export type GetInvitesSubscriberId302 =
  | (typeof GetInvitesSubscriberId302)[keyof typeof GetInvitesSubscriberId302]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInvitesSubscriberId302 = {
  null: 'null',
} as const

export type GetSubscribersSubscriberIdRankingClicks200 = {
  count: number
}

export type GetSubscriberIdRankingCount200 = {
  count: number
}

export type GetSubscribersIdRankingPosition200 = {
  /** @nullable */
  position: number | null
}

export type GetRanking200RankingItem = {
  id: string
  name: string
  score: number
}

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[]
}

/**
 * @summary Subscribe to event
 */
export const getPostSubscriptionsUrl = () => {
  return `${env.SERVER_URL}/subscriptions`
}

export const postSubscriptions = async (
  postSubscriptionsBody: PostSubscriptionsBody,
  options?: RequestInit
): Promise<PostSubscriptions201> => {
  const res = await fetch(getPostSubscriptionsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSubscriptionsBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSubscriptions201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Access Invite link and redirects user
 */
export const getGetInvitesSubscriberIdUrl = (subscriberId: string) => {
  return `${env.SERVER_URL}/invites/${subscriberId}`
}

export const getInvitesSubscriberId = async (
  subscriberId: string,
  options?: RequestInit
): Promise<unknown> => {
  const res = await fetch(getGetInvitesSubscriberIdUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: unknown = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get subscriber ranking invite clicks count
 */
export const getSubscriberIdRankingClicksUrl = (subscriberId: string) => {
  return `${env.SERVER_URL}/subscribers/${subscriberId}/ranking/clicks`
}

export const getSubscriberIdRankingClicks = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscribersSubscriberIdRankingClicks200> => {
  const res = await fetch(getSubscriberIdRankingClicksUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscribersSubscriberIdRankingClicks200 = body
    ? JSON.parse(body)
    : {}

  return data
}

/**
 * @summary Get subscriber ranking invites count
 */
export const getSubscriberIdRankingCountUrl = (subscriberId: string) => {
  return `${env.SERVER_URL}/subscribers/${subscriberId}/ranking/count`
}

export const getSubscriberIdRankingCount = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscriberIdRankingCount200> => {
  const res = await fetch(getSubscriberIdRankingCountUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscriberIdRankingCount200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get subscriber ranking position
 */
export const getSubscriberIdRankingPositionUrl = (subscriberId: string) => {
  return `${env.SERVER_URL}/subscribers/${subscriberId}/ranking/position`
}

export const getSubscriberIdRankingPosition = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscribersIdRankingPosition200> => {
  const res = await fetch(getSubscriberIdRankingPositionUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscribersIdRankingPosition200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get ranking
 */
export const getGetRankingUrl = () => {
  return `${env.SERVER_URL}/ranking`
}

export const getRanking = async (
  options?: RequestInit
): Promise<GetRanking200> => {
  const res = await fetch(getGetRankingUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetRanking200 = body ? JSON.parse(body) : {}

  return data
}
